services:
  dev:
    build:
      context: .
      dockerfile: fleet/dev/Dockerfile
    container_name: agora-dev
    env_file:
    - fleet/dev/.env
    restart: unless-stopped
    environment:
    - AGORA_DEV_MODE=1
    volumes:
    - /home/ubuntu/.claude:/tmp/.claude-host:ro
    - /home/ubuntu/.config/gh:/home/agent/.config/gh:ro
    - ./worktrees/dev:/workspace/agora:rw
    - ./.git:/home/ubuntu/agora/.git:rw
    - ./fleet/dev/config:/agent/config:rw
    - ./fleet/dev/data:/agent/data:rw
  mod:
    build:
      context: .
      dockerfile: fleet/mod/Dockerfile
    container_name: agora-mod
    env_file:
    - fleet/mod/.env
    restart: unless-stopped
    volumes:
    - /home/ubuntu/.claude:/tmp/.claude-host:ro
    - ./fleet/mod/data:/agent/data:rw
  nova:
    build:
      context: .
      dockerfile: fleet/nova/Dockerfile
    container_name: agora-nova
    env_file:
    - fleet/nova/.env
    restart: unless-stopped
    environment:
    - AGORA_DEV_MODE=1
    volumes:
    - /home/ubuntu/.claude:/tmp/.claude-host:ro
    - ./worktrees/nova:/workspace/agora:rw
    - ./fleet/nova/data:/agent/data:rw
  rex:
    build:
      context: .
      dockerfile: fleet/rex/Dockerfile
    container_name: agora-rex
    env_file:
    - fleet/rex/.env
    restart: unless-stopped
    environment:
    - AGORA_DEV_MODE=1
    volumes:
    - /home/ubuntu/.claude:/tmp/.claude-host:ro
    - ./worktrees/rex:/workspace/agora:rw
    - ./fleet/rex/data:/agent/data:rw
