"""CLI entry point for Agora commands (init, run, stop, status)."""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import signal
import sys
from datetime import date
from pathlib import Path

# Version — keep in sync with pyproject.toml
__version__ = "0.1.0"


def _slugify(name: str) -> str:
    """Convert a name to a safe directory/module identifier."""
    slug = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    slug = re.sub(r"_+", "_", slug).strip("_")
    if not slug:
        raise ValueError(f"Name '{name}' produces an empty slug")
    return slug


def _to_class_name(slug: str) -> str:
    """Convert a slug like 'my-bot' to 'MyBot'."""
    return "".join(part.capitalize() for part in re.split(r"[-_]", slug) if part)


def _validate_name(name: str) -> str:
    """Validate and return a slugified agent name."""
    slug = _slugify(name)
    # Ensure it's valid for container names (alphanumeric + hyphens)
    if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$", slug):
        raise ValueError(f"Name '{name}' is not valid. Use alphanumeric characters, hyphens, and underscores.")
    return slug


def _write_agora_metadata(project_dir: Path, template: str) -> None:
    """Write the .agora metadata file."""
    content = (
        f"# Auto-generated by agora init. Do not commit secrets here.\n"
        f"template: {template}\n"
        f"agora_version: {__version__}\n"
        f"created: {date.today().isoformat()}\n"
    )
    (project_dir / ".agora").write_text(content)


def init_agent(
    name: str,
    path: Path | None = None,
    template: str = "citizen",
    from_path: Path | None = None,
) -> Path:
    """Create a new agent project directory from a template.

    Args:
        name: Agent name (used for directory, container, registry).
        path: Where to create the directory (default: ./<name>/).
        template: Built-in template name (default: citizen).
        from_path: Custom template directory (overrides template).

    Returns the path to the created directory.
    Raises FileExistsError if the directory already exists.
    """
    from agora.templates import copy_template

    slug = _validate_name(name)
    class_name = _to_class_name(slug)

    if path is not None:
        project_dir = Path(path)
    else:
        project_dir = Path.cwd() / slug

    substitutions = {
        "name": slug,
        "class_name": class_name,
    }

    copy_template(
        template_name=template,
        dest=project_dir,
        substitutions=substitutions,
        from_path=from_path,
    )

    _write_agora_metadata(project_dir, template)

    # Auto-register
    try:
        from agora.registry import register
        register(slug, str(project_dir.resolve()), template)
    except Exception:
        pass  # Registry is advisory

    return project_dir


def _resolve_agora_source(cli_override: str | None = None) -> Path | None:
    """Resolve the agora source path for Docker builds.

    Returns None if agora is available on PyPI (future).
    Raises SystemExit with helpful error if source can't be found.
    """
    raw = cli_override or os.environ.get("AGORA_SOURCE")
    if not raw:
        # Check if agora is pip-installable from PyPI (future)
        # For now, it's not published, so error out
        print(
            "Error: agora not found on PyPI.\n"
            "Set AGORA_SOURCE=/path/to/agora in your shell profile,\n"
            "or pass --agora-source /path/to/agora.",
            file=sys.stderr,
        )
        sys.exit(1)

    source_path = Path(os.path.expanduser(raw)).resolve()
    if not (source_path / "pyproject.toml").exists():
        print(
            f"Error: AGORA_SOURCE={source_path} does not contain pyproject.toml -- check the path.",
            file=sys.stderr,
        )
        sys.exit(1)

    return source_path


def _build_context(agent_dir: Path, agora_source: Path, dockerfile: Path | None = None) -> Path:
    """Create a temp build context directory for Docker builds.

    Returns the path to the temp directory. Caller is responsible for cleanup.
    """
    import shutil
    import tempfile

    tmpdir = Path(tempfile.mkdtemp(prefix="agora-build-"))

    # Copy Dockerfile
    if dockerfile and dockerfile.exists():
        shutil.copy2(dockerfile, tmpdir / "Dockerfile")
    else:
        # Use the one from the agent directory
        agent_dockerfile = agent_dir / "Dockerfile"
        if agent_dockerfile.exists():
            shutil.copy2(agent_dockerfile, tmpdir / "Dockerfile")
        else:
            print("Error: No Dockerfile found in agent directory.", file=sys.stderr)
            shutil.rmtree(tmpdir)
            sys.exit(1)

    # Copy agora source
    agora_src_dest = tmpdir / "agora-src"
    agora_src_dest.mkdir()
    shutil.copytree(agora_source / "agora", agora_src_dest / "agora",
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    shutil.copy2(agora_source / "pyproject.toml", agora_src_dest / "pyproject.toml")
    readme = agora_source / "README.md"
    if readme.exists():
        shutil.copy2(readme, agora_src_dest / "README.md")

    # Copy agent files
    agent_dest = tmpdir / "agent"
    agent_dest.mkdir()
    for item in agent_dir.iterdir():
        if item.name in ("Dockerfile", "__pycache__", ".env", "logs", "*.log"):
            continue
        if item.name.startswith(".") and item.name != ".env.example":
            continue
        if item.is_file():
            shutil.copy2(item, agent_dest / item.name)
        elif item.is_dir() and item.name != "__pycache__":
            shutil.copytree(item, agent_dest / item.name,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    return tmpdir


def _get_agent_name(cfg, cfg_path: Path) -> str:
    """Get the agent name from config, falling back to directory name."""
    return cfg.name or cfg_path.parent.name


def _stop_existing_container(runtime: str, container_name: str) -> None:
    """Stop an existing container if running. Synchronous."""
    import subprocess
    result = subprocess.run(
        [runtime, "inspect", "--format", "{{.State.Running}}", container_name],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip().lower() == "true":
        print(f"Stopping existing container {container_name}...")
        subprocess.run([runtime, "stop", "-t", "10", container_name],
                       capture_output=True)
    # Also remove stopped container with same name (--rm may not have caught it)
    subprocess.run([runtime, "rm", "-f", container_name],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def run_agent(
    config_path: str = "agent.yaml",
    runtime_override: str | None = None,
    rebuild: bool = False,
    agora_source: str | None = None,
) -> None:
    """Run an agent based on its agent.yaml configuration."""
    import shutil

    from agora.config import Config, ConfigError
    from agora.context import ContainerContext, ContainerCrashed, ContextError, RuntimeNotFound

    cfg_path = Path(config_path)
    if not cfg_path.exists():
        print(
            "Error: No agent.yaml found. Run from an agent directory\n"
            "or use 'agora init <name>' to create one.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        cfg = Config.from_yaml(cfg_path)
    except ConfigError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    agent_dir = cfg_path.parent.resolve()
    agent_name = _get_agent_name(cfg, cfg_path)

    if cfg.context_backend is None:
        # Local mode — just run agent.py
        agent_py = agent_dir / "agent.py"
        if not agent_py.exists():
            print(f"Error: agent.py not found in {agent_dir}", file=sys.stderr)
            sys.exit(1)
        os.execvp(sys.executable, [sys.executable, str(agent_py)])
    else:
        # Container mode — resolve source, build context, run
        source_path = _resolve_agora_source(agora_source)
        container_name = f"agora-{agent_name}"
        image = cfg.context_image or agent_name
        runtime = runtime_override or cfg.context_runtime  # None = auto-detect

        # Build temp context
        build_dir = _build_context(agent_dir, source_path)

        try:
            # Auto-detect Claude credentials to mount
            mounts = []
            claude_creds = Path.home() / ".claude" / ".credentials.json"
            if claude_creds.exists():
                mounts.append(f"{claude_creds}:/home/agent/.claude/.credentials.json:ro")

            ctx = ContainerContext(
                image=image,
                runtime=runtime,
                build_path=str(build_dir),
                env_file=str(agent_dir / ".env"),
                mounts=mounts,
            )

            async def _run_container() -> int:
                try:
                    rt = await ctx.runtime()
                except RuntimeNotFound as e:
                    print(
                        f"Error: {e}\n\n"
                        "Install podman (recommended) or docker.\n"
                        "Or remove the context section from agent.yaml to run locally.",
                        file=sys.stderr,
                    )
                    return 1

                # Stop existing container with same name
                _stop_existing_container(rt, container_name)

                # Auto-register in registry
                try:
                    from agora.registry import register
                    agora_file = agent_dir / ".agora"
                    tmpl = "unknown"
                    created = None
                    if agora_file.exists():
                        for line in agora_file.read_text().splitlines():
                            if line.startswith("template:"):
                                tmpl = line.split(":", 1)[1].strip()
                            elif line.startswith("created:"):
                                created = line.split(":", 1)[1].strip()
                    register(agent_name, str(agent_dir), tmpl, created)
                except Exception:
                    pass  # Registry is advisory

                # Build
                print(f"Building image '{image}' with {rt}...")
                try:
                    await ctx.build_image(no_cache=rebuild)
                except (ContextError, OSError) as e:
                    print(f"Error building image: {e}", file=sys.stderr)
                    return 1

                # Start with container name
                print(f"Starting container {container_name}...")
                try:
                    container_id = await ctx.start(
                        name=container_name,
                    )
                except (ContextError, OSError) as e:
                    print(f"Error starting container: {e}", file=sys.stderr)
                    return 1

                # Stream logs
                log_proc = await asyncio.create_subprocess_exec(
                    rt, "logs", "-f", container_id,
                    stdout=None,
                    stderr=None,
                )

                # Wait for container to exit
                wait_proc = await asyncio.create_subprocess_exec(
                    rt, "wait", container_id,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.DEVNULL,
                )
                try:
                    stdout, _ = await wait_proc.communicate()
                except asyncio.CancelledError:
                    wait_proc.terminate()
                    log_proc.terminate()
                    print(f"\nStopping container {container_name}...")
                    await ctx.stop()
                    return 130

                log_proc.terminate()

                exit_code_str = stdout.decode().strip()
                try:
                    exit_code = int(exit_code_str)
                except ValueError:
                    exit_code = 1

                if exit_code != 0:
                    raise ContainerCrashed(
                        f"Container exited with code {exit_code}"
                    )
                return exit_code

            loop = asyncio.new_event_loop()

            def _signal_handler() -> None:
                for task in asyncio.all_tasks(loop):
                    task.cancel()

            for sig in (signal.SIGINT, signal.SIGTERM):
                loop.add_signal_handler(sig, _signal_handler)

            try:
                exit_code = loop.run_until_complete(_run_container())
            except ContainerCrashed as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            sys.exit(exit_code)
        finally:
            shutil.rmtree(build_dir, ignore_errors=True)


def stop_agent(name: str | None = None, stop_all: bool = False) -> None:
    """Stop a running agent by name, or all agents."""
    from agora.registry import load_registry
    from agora.context import detect_runtime

    if not name and not stop_all:
        print("Error: specify an agent name or use --all.", file=sys.stderr)
        sys.exit(1)

    registry = load_registry()
    citizens = registry.get("citizens", {})

    if not citizens:
        print("No agents registered.")
        return

    import shutil
    import subprocess
    runtime = None
    for rt in ("podman", "docker"):
        if shutil.which(rt):
            result = subprocess.run([rt, "info"], capture_output=True)
            if result.returncode == 0:
                runtime = rt
                break
    if not runtime:
        print("Error: no container runtime found.", file=sys.stderr)
        sys.exit(1)

    if stop_all:
        targets = list(citizens.keys())
    else:
        if name not in citizens:
            # Try anyway — might be an unregistered container
            container_name = f"agora-{name}"
            result = subprocess.run([runtime, "stop", "-t", "10", container_name],
                                    capture_output=True, text=True)
            if result.returncode == 0:
                print(f"Stopped {container_name}")
            else:
                print(f"Error: agent '{name}' not found in registry and container agora-{name} not running.",
                      file=sys.stderr)
                sys.exit(1)
            return
        targets = [name]

    for agent_name in targets:
        container_name = f"agora-{agent_name}"
        result = subprocess.run(
            [runtime, "inspect", "--format", "{{.State.Running}}", container_name],
            capture_output=True, text=True,
        )
        if result.returncode == 0 and result.stdout.strip().lower() == "true":
            subprocess.run([runtime, "stop", "-t", "10", container_name], capture_output=True)
            print(f"Stopped {container_name}")
        else:
            if not stop_all:
                print(f"{container_name} is not running.")


def show_status() -> None:
    """Show all registered agents and their state."""
    import subprocess

    from agora.registry import load_registry

    registry = load_registry()
    citizens = registry.get("citizens", {})

    # Detect runtime
    import shutil as _shutil
    runtime = None
    for rt in ("podman", "docker"):
        if _shutil.which(rt):
            result = subprocess.run([rt, "info"], capture_output=True)
            if result.returncode == 0:
                runtime = rt
                break

    # Collect status for each registered citizen
    rows = []
    for agent_name, info in citizens.items():
        path = info.get("path", "")
        template = info.get("template", "?")
        container_name = f"agora-{agent_name}"

        # Check if path exists
        if not Path(path).exists():
            rows.append((agent_name, "missing", path, template, "-"))
            continue

        # Check container state
        if runtime:
            result = subprocess.run(
                [runtime, "inspect", "--format",
                 "{{.State.Running}}|{{.State.StartedAt}}",
                 container_name],
                capture_output=True, text=True,
            )
            if result.returncode == 0:
                parts = result.stdout.strip().split("|")
                running = parts[0].lower() == "true"
                status = "running" if running else "stopped"
                # Calculate uptime
                if running and len(parts) > 1:
                    try:
                        from datetime import datetime, timezone
                        started = datetime.fromisoformat(parts[1].replace("Z", "+00:00"))
                        delta = datetime.now(timezone.utc) - started
                        hours, remainder = divmod(int(delta.total_seconds()), 3600)
                        minutes = remainder // 60
                        if hours > 0:
                            uptime = f"{hours}h{minutes}m"
                        else:
                            uptime = f"{minutes}m"
                    except Exception:
                        uptime = "?"
                else:
                    uptime = "-"
                rows.append((agent_name, status, path, template, uptime))
            else:
                rows.append((agent_name, "stopped", path, template, "-"))
        else:
            rows.append((agent_name, "?", path, template, "-"))

    # Check for unregistered agora-* containers
    if runtime:
        result = subprocess.run(
            [runtime, "ps", "--filter", "name=agora-", "--format", "{{.Names}}|{{.Status}}"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            registered_containers = {f"agora-{name}" for name in citizens}
            for line in result.stdout.strip().splitlines():
                if not line:
                    continue
                parts = line.split("|", 1)
                cname = parts[0]
                if cname not in registered_containers:
                    status_text = parts[1] if len(parts) > 1 else "running"
                    rows.append(("???", f"running (unreg)", "-", "-", status_text[:10]))

    if not rows:
        print("No agents registered. Use 'agora init <name>' to create one.")
        return

    # Print table
    print(f"{'NAME':<16} {'STATUS':<16} {'PATH':<40} {'TEMPLATE':<10} {'UPTIME':<8}")
    for name, status, path, template, uptime in rows:
        # Truncate path for display
        if len(path) > 38:
            path = "..." + path[-35:]
        print(f"{name:<16} {status:<16} {path:<40} {template:<10} {uptime:<8}")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="agora", description="Agora CLI")
    sub = parser.add_subparsers(dest="command")

    # -- init --
    init_parser = sub.add_parser("init", help="Create a new agent project")
    init_parser.add_argument("name", nargs="?", help="Name for the new agent")
    init_parser.add_argument("path", nargs="?", default=None, help="Where to create the directory (default: ./<name>/)")
    init_parser.add_argument("--template", "-t", default="citizen", help="Template to use (default: citizen)")
    init_parser.add_argument("--list", action="store_true", dest="list_templates", help="Show available templates")
    init_parser.add_argument("--from", dest="from_path", default=None, help="Custom template directory")

    # -- run --
    run_parser = sub.add_parser("run", help="Run an agent from its config")
    run_parser.add_argument("--config", default="agent.yaml", help="Path to agent.yaml")
    run_parser.add_argument("--runtime", choices=["podman", "docker"], help="Override container runtime")
    run_parser.add_argument("--rebuild", action="store_true", help="Force image rebuild (no cache)")
    run_parser.add_argument("--agora-source", default=None, help="Path to agora source (overrides AGORA_SOURCE env var)")

    # -- stop --
    stop_parser = sub.add_parser("stop", help="Stop a running agent")
    stop_parser.add_argument("name", nargs="?", help="Agent name to stop")
    stop_parser.add_argument("--all", action="store_true", dest="stop_all", help="Stop all running agents")

    # -- status --
    sub.add_parser("status", help="Show all registered agents and their state")

    args = parser.parse_args(argv)

    if args.command == "init":
        if args.list_templates:
            from agora.templates import list_templates
            templates = list_templates()
            for name, meta in templates.items():
                mode = "container" if meta.get("container") else "local"
                print(f"  {name:12s} {meta['description']} ({mode})")
            return

        if not args.name:
            print("Error: name is required. Usage: agora init <name> [path]", file=sys.stderr)
            sys.exit(1)

        try:
            from_path = Path(args.from_path) if args.from_path else None
            dest = Path(args.path) if args.path else None
            path = init_agent(
                args.name,
                path=dest,
                template=args.template,
                from_path=from_path,
            )
            print(f"Created agent '{args.name}' at {path}")
            print(f"Next: edit {path}/CLAUDE.md and {path}/.env, then run 'agora run'")
        except (FileExistsError, ValueError) as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    elif args.command == "run":
        run_agent(
            config_path=args.config,
            runtime_override=args.runtime,
            rebuild=args.rebuild,
            agora_source=args.agora_source,
        )
    elif args.command == "stop":
        stop_agent(name=args.name, stop_all=args.stop_all)
    elif args.command == "status":
        show_status()
    else:
        parser.print_help()
        sys.exit(1)
