"""CLI entry point for Agora commands (init, run, stop, status)."""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import signal
import sys
from datetime import date
from pathlib import Path

# Version — keep in sync with pyproject.toml
__version__ = "0.1.0"


def _slugify(name: str) -> str:
    """Convert a name to a safe directory/module identifier."""
    slug = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    slug = re.sub(r"_+", "_", slug).strip("_")
    if not slug:
        raise ValueError(f"Name '{name}' produces an empty slug")
    return slug


def _to_class_name(slug: str) -> str:
    """Convert a slug like 'my-bot' to 'MyBot'."""
    return "".join(part.capitalize() for part in re.split(r"[-_]", slug) if part)


def _validate_name(name: str) -> str:
    """Validate and return a slugified agent name."""
    slug = _slugify(name)
    # Ensure it's valid for container names (alphanumeric + hyphens)
    if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$", slug):
        raise ValueError(f"Name '{name}' is not valid. Use alphanumeric characters, hyphens, and underscores.")
    return slug


def _write_agora_metadata(project_dir: Path, template: str) -> None:
    """Write the .agora metadata file."""
    content = (
        f"# Auto-generated by agora init. Do not commit secrets here.\n"
        f"template: {template}\n"
        f"agora_version: {__version__}\n"
        f"created: {date.today().isoformat()}\n"
    )
    (project_dir / ".agora").write_text(content)


def compose_service_block(agent_dir: Path) -> dict:
    """Generate a docker-compose service dict from an agent directory.

    Args:
        agent_dir: Path to an agent directory containing agent.yaml.

    Returns:
        Dict of {name: service_config} suitable for merging into compose services.
    """
    import yaml

    cfg_path = agent_dir / "agent.yaml"
    if not cfg_path.exists():
        raise FileNotFoundError(f"No agent.yaml in {agent_dir}")
    with open(cfg_path) as f:
        cfg = yaml.safe_load(f)

    name = cfg.get("name", agent_dir.name)

    # Use paths relative to cwd (compose context) so the file is portable
    try:
        rel_dir = agent_dir.resolve().relative_to(Path.cwd().resolve())
    except ValueError:
        rel_dir = agent_dir

    service = {
        "build": {
            "context": ".",
            "dockerfile": str(rel_dir / "Dockerfile"),
        },
        "container_name": f"agora-{name}",
        "env_file": [str(rel_dir / ".env")],
        "restart": "unless-stopped",
    }

    # Mount Claude credentials if available on host
    claude_creds = Path.home() / ".claude" / ".credentials.json"
    if claude_creds.exists():
        service["volumes"] = [
            f"{claude_creds}:/home/agent/.claude/.credentials.json:ro"
        ]

    return {name: service}


def _is_repo_root(path: Path | None = None) -> bool:
    """Check if path looks like the agora repo root (has agora/ and .git/)."""
    p = path or Path.cwd()
    return (p / "agora").is_dir() and (p / ".git").exists()


def _append_compose_service(agent_dir: Path) -> None:
    """Append a service block to docker-compose.yml, creating it if needed."""
    import yaml

    compose_path = Path.cwd() / "docker-compose.yml"
    if compose_path.exists():
        with open(compose_path) as f:
            compose = yaml.safe_load(f) or {}
    else:
        compose = {}

    if "services" not in compose:
        compose["services"] = {}

    block = compose_service_block(agent_dir)
    compose["services"].update(block)

    with open(compose_path, "w") as f:
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)


def init_agent(
    name: str,
    path: Path | None = None,
    template: str = "citizen",
    from_path: Path | None = None,
) -> Path:
    """Create a new agent project directory from a template.

    Args:
        name: Agent name (used for directory, container, registry).
        path: Where to create the directory (default: fleet/<name>/ at repo root).
        template: Built-in template name (default: citizen).
        from_path: Custom template directory (overrides template).

    Returns the path to the created directory.
    Raises FileExistsError if the directory already exists.
    """
    from agora.templates import copy_template

    slug = _validate_name(name)
    class_name = _to_class_name(slug)

    if path is not None:
        project_dir = Path(path)
    elif _is_repo_root():
        project_dir = Path.cwd() / "fleet" / slug
    else:
        project_dir = Path.cwd() / slug

    if project_dir.exists():
        raise FileExistsError(f"{project_dir} already exists.")

    display_name = slug.replace("-", " ").replace("_", " ").title()
    token_env = f"AGORA_{slug.upper().replace('-', '_')}_TOKEN"

    substitutions = {
        "name": slug,
        "class_name": class_name,
        "display_name": display_name,
        "token_env": token_env,
    }

    copy_template(
        template_name=template,
        dest=project_dir,
        substitutions=substitutions,
        from_path=from_path,
    )

    _write_agora_metadata(project_dir, template)

    # Append to docker-compose.yml if agent is in fleet/
    fleet_dir = Path.cwd() / "fleet"
    if _is_repo_root() and project_dir.resolve().is_relative_to(fleet_dir.resolve()):
        try:
            _append_compose_service(project_dir)
        except Exception:
            pass  # Compose append is advisory

    return project_dir


def _resolve_agora_source(cli_override: str | None = None) -> Path | None:
    """Resolve the agora source path for Docker builds.

    Returns None if agora is available on PyPI (future).
    Raises SystemExit with helpful error if source can't be found.
    """
    raw = cli_override or os.environ.get("AGORA_SOURCE")
    if not raw:
        # Check if agora is pip-installable from PyPI (future)
        # For now, it's not published, so error out
        print(
            "Error: agora not found on PyPI.\n"
            "Set AGORA_SOURCE=/path/to/agora in your shell profile,\n"
            "or pass --agora-source /path/to/agora.",
            file=sys.stderr,
        )
        sys.exit(1)

    source_path = Path(os.path.expanduser(raw)).resolve()
    if not (source_path / "pyproject.toml").exists():
        print(
            f"Error: AGORA_SOURCE={source_path} does not contain pyproject.toml -- check the path.",
            file=sys.stderr,
        )
        sys.exit(1)

    return source_path


def _build_context(agent_dir: Path, agora_source: Path, dockerfile: Path | None = None) -> Path:
    """Create a temp build context directory for Docker builds.

    Returns the path to the temp directory. Caller is responsible for cleanup.
    """
    import shutil
    import tempfile

    tmpdir = Path(tempfile.mkdtemp(prefix="agora-build-"))

    # Copy Dockerfile
    if dockerfile and dockerfile.exists():
        shutil.copy2(dockerfile, tmpdir / "Dockerfile")
    else:
        # Use the one from the agent directory
        agent_dockerfile = agent_dir / "Dockerfile"
        if agent_dockerfile.exists():
            shutil.copy2(agent_dockerfile, tmpdir / "Dockerfile")
        else:
            print("Error: No Dockerfile found in agent directory.", file=sys.stderr)
            shutil.rmtree(tmpdir)
            sys.exit(1)

    # Copy agora source (matches Dockerfile: COPY agora/ + COPY pyproject.toml)
    shutil.copytree(agora_source / "agora", tmpdir / "agora",
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    shutil.copy2(agora_source / "pyproject.toml", tmpdir / "pyproject.toml")

    # Copy agent files into fleet/<name>/ (matches Dockerfile: COPY fleet/<name>/)
    agent_name = agent_dir.name
    agent_dest = tmpdir / "fleet" / agent_name
    agent_dest.mkdir(parents=True)
    for item in agent_dir.iterdir():
        if item.name in ("Dockerfile", "__pycache__", ".env", "logs", "*.log"):
            continue
        if item.name.startswith(".") and item.name != ".env.example":
            continue
        if item.is_file():
            shutil.copy2(item, agent_dest / item.name)
        elif item.is_dir() and item.name != "__pycache__":
            shutil.copytree(item, agent_dest / item.name,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    return tmpdir


def _get_agent_name(cfg, cfg_path: Path) -> str:
    """Get the agent name from config, falling back to directory name."""
    return cfg.name or cfg_path.parent.name


def _stop_existing_container(runtime: str, container_name: str) -> None:
    """Stop an existing container if running. Synchronous."""
    import subprocess
    result = subprocess.run(
        [runtime, "inspect", "--format", "{{.State.Running}}", container_name],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip().lower() == "true":
        print(f"Stopping existing container {container_name}...")
        subprocess.run([runtime, "stop", "-t", "10", container_name],
                       capture_output=True)
    # Also remove stopped container with same name (--rm may not have caught it)
    subprocess.run([runtime, "rm", "-f", container_name],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def run_agent(
    config_path: str = "agent.yaml",
    runtime_override: str | None = None,
    rebuild: bool = False,
    agora_source: str | None = None,
) -> None:
    """Run an agent based on its agent.yaml configuration."""
    import shutil

    from agora.config import Config, ConfigError
    from agora.context import ContainerContext, ContainerCrashed, ContextError, RuntimeNotFound

    cfg_path = Path(config_path)
    if not cfg_path.exists():
        print(
            "Error: No agent.yaml found. Run from an agent directory\n"
            "or use 'agora init <name>' to create one.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        cfg = Config.from_yaml(cfg_path)
    except ConfigError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    agent_dir = cfg_path.parent.resolve()
    agent_name = _get_agent_name(cfg, cfg_path)

    if cfg.context_backend is None:
        # Local mode — just run agent.py
        agent_py = agent_dir / "agent.py"
        if not agent_py.exists():
            print(f"Error: agent.py not found in {agent_dir}", file=sys.stderr)
            sys.exit(1)
        os.execvp(sys.executable, [sys.executable, str(agent_py)])
    else:
        # Container mode — resolve source, build context, run
        source_path = _resolve_agora_source(agora_source)
        container_name = f"agora-{agent_name}"
        image = cfg.context_image or agent_name
        runtime = runtime_override or cfg.context_runtime  # None = auto-detect

        # Build temp context
        build_dir = _build_context(agent_dir, source_path)

        try:
            # Auto-detect Claude credentials to mount
            mounts = []
            claude_creds = Path.home() / ".claude" / ".credentials.json"
            if claude_creds.exists():
                mounts.append(f"{claude_creds}:/home/agent/.claude/.credentials.json:ro")

            ctx = ContainerContext(
                image=image,
                runtime=runtime,
                build_path=str(build_dir),
                env_file=str(agent_dir / ".env"),
                mounts=mounts,
            )

            async def _run_container() -> int:
                try:
                    rt = await ctx.runtime()
                except RuntimeNotFound as e:
                    print(
                        f"Error: {e}\n\n"
                        "Install podman (recommended) or docker.\n"
                        "Or remove the context section from agent.yaml to run locally.",
                        file=sys.stderr,
                    )
                    return 1

                # Stop existing container with same name
                _stop_existing_container(rt, container_name)

                # Build
                print(f"Building image '{image}' with {rt}...")
                try:
                    await ctx.build_image(no_cache=rebuild)
                except (ContextError, OSError) as e:
                    print(f"Error building image: {e}", file=sys.stderr)
                    return 1

                # Start with container name
                print(f"Starting container {container_name}...")
                try:
                    container_id = await ctx.start(
                        name=container_name,
                    )
                except (ContextError, OSError) as e:
                    print(f"Error starting container: {e}", file=sys.stderr)
                    return 1

                # Stream logs
                log_proc = await asyncio.create_subprocess_exec(
                    rt, "logs", "-f", container_id,
                    stdout=None,
                    stderr=None,
                )

                # Wait for container to exit
                wait_proc = await asyncio.create_subprocess_exec(
                    rt, "wait", container_id,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.DEVNULL,
                )
                try:
                    stdout, _ = await wait_proc.communicate()
                except asyncio.CancelledError:
                    wait_proc.terminate()
                    log_proc.terminate()
                    print(f"\nStopping container {container_name}...")
                    await ctx.stop()
                    return 130

                log_proc.terminate()

                exit_code_str = stdout.decode().strip()
                try:
                    exit_code = int(exit_code_str)
                except ValueError:
                    exit_code = 1

                if exit_code != 0:
                    raise ContainerCrashed(
                        f"Container exited with code {exit_code}"
                    )
                return exit_code

            loop = asyncio.new_event_loop()

            def _signal_handler() -> None:
                for task in asyncio.all_tasks(loop):
                    task.cancel()

            for sig in (signal.SIGINT, signal.SIGTERM):
                loop.add_signal_handler(sig, _signal_handler)

            try:
                exit_code = loop.run_until_complete(_run_container())
            except ContainerCrashed as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            sys.exit(exit_code)
        finally:
            shutil.rmtree(build_dir, ignore_errors=True)


def stop_agent(name: str | None = None, stop_all: bool = False) -> None:
    """Stop a running agent by name, or all agents via fleet stop."""
    import subprocess

    if stop_all:
        sys.exit(fleet_stop())

    if not name:
        print("Error: specify an agent name or use --all.", file=sys.stderr)
        sys.exit(1)

    runtime = _detect_runtime()
    if not runtime:
        print("Error: no container runtime found.", file=sys.stderr)
        sys.exit(1)

    container_name = f"agora-{name}"
    result = subprocess.run(
        [runtime, "stop", "-t", "10", container_name],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(f"Stopped {container_name}")
    else:
        print(f"Error: container {container_name} not running.", file=sys.stderr)
        sys.exit(1)


def show_status() -> None:
    """Show agent status — delegates to fleet_status."""
    fleet_status()


def _detect_runtime() -> str | None:
    """Detect available container runtime (podman or docker)."""
    import shutil
    import subprocess as _sp
    for rt in ("podman", "docker"):
        if shutil.which(rt):
            result = _sp.run([rt, "info"], capture_output=True)
            if result.returncode == 0:
                return rt
    return None



def _scan_fleet() -> list[Path]:
    """Scan fleet/ for agent directories containing agent.yaml."""
    fleet_dir = Path.cwd() / "fleet"
    if not fleet_dir.is_dir():
        return []
    return sorted(
        d for d in fleet_dir.iterdir()
        if d.is_dir() and (d / "agent.yaml").exists()
    )


def _ensure_compose(agents: list[Path] | None = None) -> Path:
    """Ensure docker-compose.yml exists, regenerating from fleet/ if missing."""
    import yaml

    compose_path = Path.cwd() / "docker-compose.yml"
    if compose_path.exists():
        return compose_path

    if agents is None:
        agents = _scan_fleet()

    if not agents:
        raise FileNotFoundError("No agents in fleet/ and no docker-compose.yml")

    compose = {"services": {}}
    for agent_dir in agents:
        block = compose_service_block(agent_dir)
        compose["services"].update(block)

    with open(compose_path, "w") as f:
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

    return compose_path


def fleet_start(build: bool = False) -> int:
    """Start fleet using docker compose.

    When --build is passed, builds and starts each service individually
    to isolate failures. Otherwise, just starts existing images.
    Returns the number of failures.
    """
    import subprocess as _sp

    runtime = _detect_runtime()
    if not runtime:
        print("Error: no container runtime (docker/podman) found.", file=sys.stderr)
        return 1

    agents = _scan_fleet()
    if not agents:
        print("No agents in fleet/. Use 'agora init <name>' to create one.")
        return 0

    try:
        compose_path = _ensure_compose(agents)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    # Validate .env files
    for agent_dir in agents:
        env_file = agent_dir / ".env"
        if not env_file.exists():
            print(f"  Warning: {env_file} not found — {agent_dir.name} may fail to start")

    # Read service names from compose
    import yaml
    with open(compose_path) as f:
        compose = yaml.safe_load(f) or {}
    services = list((compose.get("services") or {}).keys())

    if not services:
        print("No services in docker-compose.yml.")
        return 0

    compose_cmd = [runtime, "compose"] if runtime == "docker" else ["podman-compose"]

    failures = 0
    for svc in services:
        print(f"Starting {svc}...", end=" ", flush=True)

        if build:
            result = _sp.run(
                [*compose_cmd, "build", svc],
                capture_output=True, text=True, cwd=str(Path.cwd()),
            )
            if result.returncode != 0:
                print("BUILD FAILED")
                print(f"  {result.stderr.strip()[:200]}")
                failures += 1
                continue

        # Up
        result = _sp.run(
            [*compose_cmd, "up", "-d", svc],
            capture_output=True, text=True, cwd=str(Path.cwd()),
        )
        if result.returncode != 0:
            print("START FAILED")
            print(f"  {result.stderr.strip()[:200]}")
            failures += 1
        else:
            print("ok")

    total = len(services)
    ok = total - failures
    print(f"Fleet: {ok}/{total} started ({failures} failed)")
    return failures


def fleet_stop() -> int:
    """Stop fleet using docker compose down.

    Returns the number of failures (0 or 1).
    """
    import subprocess as _sp

    runtime = _detect_runtime()
    if not runtime:
        print("Error: no container runtime found.", file=sys.stderr)
        return 1

    compose_cmd = [runtime, "compose"] if runtime == "docker" else ["podman-compose"]
    result = _sp.run(
        [*compose_cmd, "down"],
        capture_output=True, text=True, cwd=str(Path.cwd()),
    )
    if result.returncode != 0:
        print(f"Error: {result.stderr.strip()}", file=sys.stderr)
        return 1

    print("Fleet stopped.")
    return 0


def fleet_status() -> None:
    """Show fleet status using docker compose ps."""
    import subprocess as _sp

    runtime = _detect_runtime()
    if not runtime:
        print("No container runtime found.")
        return

    compose_cmd = [runtime, "compose"] if runtime == "docker" else ["podman-compose"]
    result = _sp.run(
        [*compose_cmd, "ps", "-a"],
        capture_output=True, text=True, cwd=str(Path.cwd()),
    )
    if result.returncode == 0 and result.stdout.strip():
        print(result.stdout)
    else:
        print("No fleet containers running.")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="agora", description="Agora CLI")
    sub = parser.add_subparsers(dest="command")

    # -- init --
    init_parser = sub.add_parser("init", help="Create a new agent project")
    init_parser.add_argument("name", nargs="?", help="Name for the new agent")
    init_parser.add_argument("path", nargs="?", default=None, help="Where to create the directory (default: ./<name>/)")
    init_parser.add_argument("--template", "-t", default="citizen", help="Template to use (default: citizen)")
    init_parser.add_argument("--list", action="store_true", dest="list_templates", help="Show available templates")
    init_parser.add_argument("--from", dest="from_path", default=None, help="Custom template directory")

    # -- run --
    run_parser = sub.add_parser("run", help="Run an agent from its config")
    run_parser.add_argument("--config", default="agent.yaml", help="Path to agent.yaml")
    run_parser.add_argument("--runtime", choices=["podman", "docker"], help="Override container runtime")
    run_parser.add_argument("--rebuild", action="store_true", help="Force image rebuild (no cache)")
    run_parser.add_argument("--agora-source", default=None, help="Path to agora source (overrides AGORA_SOURCE env var)")

    # -- stop --
    stop_parser = sub.add_parser("stop", help="Stop a running agent")
    stop_parser.add_argument("name", nargs="?", help="Agent name to stop")
    stop_parser.add_argument("--all", action="store_true", dest="stop_all", help="Stop all running agents")

    # -- status --
    sub.add_parser("status", help="Show all registered agents and their state")

    # -- fleet --
    fleet_parser = sub.add_parser("fleet", help="Fleet management commands")
    fleet_sub = fleet_parser.add_subparsers(dest="fleet_command")

    start_parser = fleet_sub.add_parser("start", help="Start all fleet agents")
    start_parser.add_argument("--build", action="store_true", help="Rebuild images before starting")
    fleet_sub.add_parser("stop", help="Stop all fleet agents")
    fleet_sub.add_parser("status", help="Show fleet container status")

    args = parser.parse_args(argv)

    if args.command == "init":
        if args.list_templates:
            from agora.templates import list_templates
            templates = list_templates()
            for name, meta in templates.items():
                mode = "container" if meta.get("container") else "local"
                print(f"  {name:12s} {meta['description']} ({mode})")
            return

        if not args.name:
            print("Error: name is required. Usage: agora init <name> [path]", file=sys.stderr)
            sys.exit(1)

        try:
            from_path = Path(args.from_path) if args.from_path else None
            dest = Path(args.path) if args.path else None
            path = init_agent(
                args.name,
                path=dest,
                template=args.template,
                from_path=from_path,
            )
            print(f"Created agent '{args.name}' at {path}/")
            print(f"  (not tracked by git — customize freely)")
            print(f"Next steps:")
            print(f"  1. cp {path}/.env.example {path}/.env")
            print(f"  2. Add your bot token to {path}/.env")
            print(f"  3. (Optional) Edit {path}/agent.yaml and {path}/CLAUDE.md")
            print(f"  4. Run: agora fleet start")
        except (FileExistsError, ValueError) as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    elif args.command == "run":
        run_agent(
            config_path=args.config,
            runtime_override=args.runtime,
            rebuild=args.rebuild,
            agora_source=args.agora_source,
        )
    elif args.command == "stop":
        stop_agent(name=args.name, stop_all=args.stop_all)
    elif args.command == "status":
        show_status()
    elif args.command == "fleet":
        if args.fleet_command == "start":
            failures = fleet_start(build=args.build)
            sys.exit(failures)
        elif args.fleet_command == "stop":
            failures = fleet_stop()
            sys.exit(failures)
        elif args.fleet_command == "status":
            fleet_status()
        else:
            fleet_parser.print_help()
            sys.exit(1)
    else:
        parser.print_help()
        sys.exit(1)
